-- upto date as of 9 Dec 2012.
-- in future , if there are any sqls here , execute them after following the instructions at mycp.ddl.sql file.
--Start Gangu
update jbpm4_lob set blob_value_='<?xml version=\"1.0\" encoding=\"UTF-8\"?><process name=\"Compute Request\" key=\"Compute_Request\" xmlns=\"http://jbpm.org/4.4/jpdl\"><start><transition to=\"Verification by Admin\" /></start><state name=\"Verification by Admin\"><transition name=\"Approve\" to=\"Approval by Manager\" /><transition name=\"Reject\" to=\"Rejected\" /></state><state name=\"Approval by Manager\"><transition name=\"Approve\" to=\"Approved\"/><transition name=\"Reject\" to=\"Rejected\"/></state><end name=\"Approved\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceApprovalTemplate\"/></field></event-listener></on></end><end-cancel name=\"Rejected\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceRejectTemplate\"/></field></event-listener></on></end-cancel></process>' where dbid_=81007;
update jbpm4_lob set blob_value_='<?xml version=\"1.0\\
" encoding=\"UTF-8\"?><process name=\"Image Request\" key=\"Image_Request\" xmlns=\"http://jbpm.org/4.4/jpdl\"><start>   <transition to=\"Verification by Admin\" /> </start><state name=\"Verification by Admin\"><transition name=\"Approve\" to=\"Approval by Manager\" /><transition name=\"Reject\" to=\"Rejected\" /></state><state name=\"Approval by Manager\"><transition name=\"Approve\" to=\"Approved\"/><transition name=\"Reject\" to=\"Rejected\"/></state><end name=\"Approved\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceApprovalTemplate\"/></field></event-listener></on></end><end-cancel name=\"Rejected\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceRejectTemplate\"/></field></event-listener></on></end-cancel></process>' where dbid_=81013;
update jbpm4_lob set blob_value_='<?xml version=\"1.0\" encoding=\"UTF-8\"?><process name=\"IpAddress Request\" key=\"IpAddress_Request\" xmlns=\"http://jbpm.org/4.4/jpdl\"><start>   <transition to=\"Verification by Admin\" /> </start><state name=\"Verification by Admin\"><transition name=\"Approve\" to=\"Approval by Manager\" /><transition name=\"Reject\" to=\"Rejected\" /></state><state name=\"Approval by Manager\"><transition name=\"Approve\" to=\"Approved\"/><transition name=\"Reject\" to=\"Rejected\"/></state><end name=\"Approved\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceApprovalTemplate\"/></field></event-listener></on></end><end-cancel name=\"Rejected\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceRejectTemplate\"/></field></event-listener></on></end-cancel></process>' where dbid_=81019;
update jbpm4_lob set blob_value_='<?xml version=\"1.0\" encoding=\"UTF-8\"?><process name=\"Keys Request\" key=\"Keys_Request\" xmlns=\"http://jbpm.org/4.4/jpdl\"><start>   <transition to=\"Verification by Admin\" /> </start><state name=\"Verification by Admin\"><transition name=\"Approve\" to=\"Approval by Manager\" /><transition name=\"Reject\" to=\"Rejected\" /></state><state name=\"Approval by Manager\"><transition name=\"Approve\" to=\"Approved\"/><transition name=\"Reject\" to=\"Rejected\"/></state><end name=\"Approved\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceApprovalTemplate\"/></field></event-listener></on></end><end-cancel name=\"Rejected\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceRejectTemplate\"/></field></event-listener></on></end-cancel></process>' where dbid_=81025;
update jbpm4_lob set blob_value_='<?xml version=\"1.0\" encoding=\"UTF-8\"?><process name=\"SecGroup Request\" key=\"SecGroup_Request\" xmlns=\"http://jbpm.org/4.4/jpdl\"><start>   <transition to=\"Verification by Admin\" /> </start><state name=\"Verification by Admin\"><transition name=\"Approve\" to=\"Approval by Manager\" /><transition name=\"Reject\" to=\"Rejected\" /></state><state name=\"Approval by Manager\"><transition name=\"Approve\" to=\"Approved\"/><transition name=\"Reject\" to=\"Rejected\"/></state><end name=\"Approved\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceApprovalTemplate\"/></field></event-listener></on></end><end-cancel name=\"Rejected\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceRejectTemplate\"/></field></event-listener></on></end-cancel></process>' where dbid_=81031;
update jbpm4_lob set blob_value_='<?xml version=\"1.0\" encoding=\"UTF-8\"?><process name=\"Snapshot Request\" key=\"Snapshot_Request\" xmlns=\"http://jbpm.org/4.4/jpdl\"><start>   <transition to=\"Verification by Admin\" /> </start><state name=\"Verification by Admin\"><transition name=\"Approve\" to=\"Approval by Manager\" /><transition name=\"Reject\" to=\"Rejected\" /></state><state name=\"Approval by Manager\"><transition name=\"Approve\" to=\"Approved\"/><transition name=\"Reject\" to=\"Rejected\"/></state><end name=\"Approved\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceApprovalTemplate\"/></field></event-listener></on></end><end-cancel name=\"Rejected\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceRejectTemplate\"/></field></event-listener></on></end-cancel></process>' where dbid_=81037;
update jbpm4_lob set blob_value_='<?xml version=\"1.0\" encoding=\"UTF-8\"?><process name=\"Volume Request\" key=\"Volume_Request\" xmlns=\"http://jbpm.org/4.4/jpdl\"><start>   <transition to=\"Verification by Admin\" /> </start><state name=\"Verification by Admin\"><transition name=\"Approve\" to=\"Approval by Manager\" /><transition name=\"Reject\" to=\"Rejected\" /></state><state name=\"Approval by Manager\"><transition name=\"Approve\" to=\"Approved\"/><transition name=\"Reject\" to=\"Rejected\"/></state><end name=\"Approved\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceApprovalTemplate\"/></field></event-listener></on></end><end-cancel name=\"Rejected\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"><field name=\"mailTemplate\"><string value=\"ResourceRejectTemplate\"/></field></event-listener></on></end-cancel></process>' where dbid_=81043;
update jbpm4_lob set blob_value_='<?xml version=\"1.0\" encoding=\"UTF-8\"?><process xmlns=\"http://jbpm.org/4.4/jpdl\" name=\"Mail4Users\">   <start name=\"start1\"><transition name=\"to sendMail\" to=\"sendMail\"/>   </start>   <state name=\"sendMail\" to=\"end\"><on event=\"start\"><event-listener class=\"in.mycp.job.JbpmMailEventListener\"/></on>   </state>   <end name=\"end\"/></process>' where dbid_=81044;
update jbpm4_lob set blob_value_='<?xml version=\"1.0\" encoding=\"UTF-8\"?><process name=\"QuotaExceedCheck\" xmlns=\"http://jbpm.org/4.4/jpdl\">  <start>    <transition to=\"Quotacheck\" />  </start>  <state name=\"Quotacheck\">    <on event=\"timeout\">      <timer duedate=\"10 minutes\" repeat=\"10 seconds\" />      <event-listener class=\"in.mycp.service.ApplicationContextService4Jobs\" />    </on>    <transition name=\"go on\" to=\"next step\"/>  </state>  <state name=\"next step\"/></process>' where dbid_=81045;
commit;
--End 

-- Start charu - 11 Dec 2012

ALTER TABLE `mycp`.`address_info_p` CHANGE COLUMN `associated` `associated` TINYINT(1) NULL DEFAULT 0  , 
CHANGE COLUMN `automatic` `automatic` TINYINT(1) NULL DEFAULT 0  , 
ADD COLUMN `assigned` TINYINT(1) NULL DEFAULT 0  AFTER `automatic` ;

ALTER TABLE `mycp`.`address_info_p` DROP COLUMN `assigned` , DROP COLUMN `automatic` , DROP COLUMN `associated` ;

-- End charu - 11 Dec 2012

ALTER TABLE `mycp`.`group_description_p` CHANGE COLUMN `name` `name` VARCHAR(90) NULL DEFAULT NULL  ;
ALTER TABLE `mycp`.`instance_p` CHANGE COLUMN `keyName` `keyName` VARCHAR(90) NULL DEFAULT NULL  , 
CHANGE COLUMN `groupName` `groupName` VARCHAR(90) NULL DEFAULT NULL  ;



