// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.mycp.domain;

import in.mycp.domain.Asset;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Asset_Roo_Configurable {
    
    declare @type: Asset: @Configurable;
    
}
