// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.mycp.domain;

import in.mycp.domain.GroupDescriptionP;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GroupDescriptionP_Roo_Configurable {
    
    declare @type: GroupDescriptionP: @Configurable;
    
}
