// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.mycp.domain;

import in.mycp.domain.Asset;
import in.mycp.domain.InstanceP;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect InstanceP_Roo_Finder {
    
    
    
}
