// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.mycp.domain;

import in.mycp.domain.UserProjectPK;
import java.io.Serializable;

privileged aspect UserProjectPK_Roo_Serializable {
    
    declare parents: UserProjectPK implements Serializable;
    
    private static final long UserProjectPK.serialVersionUID = 1L;
    
}
